"use client";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, LockKeyhole, Map, Play, Star } from "lucide-react";
import { useRouter } from "next/navigation";
type Level = { level:number;visible:boolean;unlocked:boolean;completed:boolean;bestTimeMs:number|null;rating:number };
export function MazeLobby(){
  const router=useRouter(),[levels,setLevels]=useState<Level[]>([]),[second,setSecond]=useState(false),[group,setGroup]=useState<1|2>(1),[message,setMessage]=useState("");
  useEffect(()=>{void fetch("/api/games/maze-runner/progress",{cache:"no-store"}).then(async r=>{const b=await r.json();if(r.ok){setLevels(b.levels);setSecond(b.secondSetUnlocked)}else setMessage(b.error)})},[]);
  async function play(level:number){setMessage("");const r=await fetch("/api/games/maze-runner/attempts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({level})}),b=await r.json();if(!r.ok)return setMessage(b.error??"Could not start");router.push(`/games/maze-runner/play?attempt=${encodeURIComponent(b.attempt.publicReference)}`)}
  const visible=levels.filter(l=>l.level>(group-1)*10&&l.level<=group*10);
  return <main className="mx-auto min-h-dvh max-w-3xl px-3 pb-8 pt-4 sm:px-6"><header className="rounded-[2rem] bg-ink p-6 text-white shadow-float"><p className="text-xs font-black uppercase tracking-[.18em] text-teal-300">Explore · Solve · Escape</p><h1 className="mt-2 text-3xl font-black">Maze Runner</h1><p className="mt-2 max-w-xl text-sm text-white/70">Navigate deterministic mazes, collect keys, open gates, avoid traps, and reach the glowing exit.</p></header>
  <section className="mt-4 rounded-3xl bg-white p-4 shadow-card"><div className="flex items-center justify-between gap-2"><button disabled={group===1} onClick={()=>setGroup(1)} className="game-secondary px-3"><ArrowLeft size={16}/>Previous 10</button><strong>Levels {group===1?"1–10":"11–20"}</strong><button disabled={!second||group===2} onClick={()=>setGroup(2)} className="game-secondary px-3">Next 10<ArrowRight size={16}/></button></div>
  <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-5">{visible.map(level=><button key={level.level} disabled={!level.unlocked} onClick={()=>void play(level.level)} className={`min-h-28 rounded-2xl border p-3 text-left ${level.unlocked?"border-teal-100 bg-teal-50":"border-warm-100 bg-warm-50 text-warm-400"}`}><span className="flex items-center justify-between"><b>Level {level.level}</b>{level.unlocked?<Play size={15}/>:<LockKeyhole size={15}/>}</span>{level.completed?<><span className="mt-3 block text-xs">{(level.bestTimeMs!/1000).toFixed(1)}s best</span><span className="mt-1 flex text-amber-500">{Array.from({length:level.rating},(_,i)=><Star key={i} size={13} fill="currentColor"/>)}</span></>:<span className="mt-3 block text-xs">{level.unlocked?"Ready":"Locked"}</span>}</button>)}</div></section>
  <details className="mt-4 rounded-3xl bg-white p-5 shadow-card"><summary className="cursor-pointer font-black">How to Play Maze Runner</summary><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm text-warm-600"><li>Swipe, tap an adjacent path, or use the direction controls.</li><li>Find the route to the glowing exit.</li><li>Collect keys before crossing locked gates.</li><li>Avoid marked trap tiles.</li><li>Complete each level to unlock the next.</li><li>Finish Levels 1–10 to reveal Levels 11–20.</li></ol><p className="mt-3 text-xs font-bold text-teal-700">Ads are optional and are never required to start a normal level.</p></details>
  {message&&<p className="mt-3 rounded-2xl bg-coral-50 p-3 text-sm font-bold text-coral-700">{message}</p>}</main>
}
