import { z } from "zod";
import { getSession, requireSession } from "@/lib/session";
import { cookies } from "next/headers";
import { hashDeviceIdentifier, hashStatusAccessToken, requestStatusCookieName, REQUEST_DEVICE_COOKIE, REQUEST_DEVICE_MAX_AGE } from "@/features/mini-app-requests/device";
import { assertSameOrigin } from "@/features/profile/security";
import { applicantRequest, respondToInformation } from "@/features/mini-app-requests/server";
export async function GET(request:Request,{params}:{params:Promise<{publicReference:string}>}){try{const auth=await getSession(),{publicReference}=await params,jar=await cookies(),rawDevice=jar.get(REQUEST_DEVICE_COOKIE)?.value;const supplied=new URL(request.url).searchParams.get("access")??request.headers.get("x-status-access-token")??jar.get(requestStatusCookieName(publicReference))?.value;const item=await applicantRequest({userId:auth?.userId,reference:publicReference,deviceIdentifierHash:rawDevice?hashDeviceIdentifier(rawDevice):undefined,statusAccessTokenHash:supplied?hashStatusAccessToken(supplied):undefined});if(!item)return Response.json({error:"Request not found or access denied."},{status:404});const response=Response.json(item);if(supplied)response.headers.append("Set-Cookie",`${requestStatusCookieName(publicReference)}=${supplied}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${REQUEST_DEVICE_MAX_AGE}${process.env.NODE_ENV==="production"?"; Secure":""}`);return response}catch{return Response.json({error:"Could not load request."},{status:500})}}
const schema=z.object({message:z.string().trim().min(20).max(2000)}).strict();
export async function POST(request:Request,{params}:{params:Promise<{publicReference:string}>}){try{assertSameOrigin(request);const auth=await requireSession(),{publicReference}=await params,input=schema.parse(await request.json());await respondToInformation(auth.userId,publicReference,input.message);return Response.json({ok:true})}catch(error){if(error instanceof Response)return error;return Response.json({error:error instanceof z.ZodError?error.issues[0]?.message:"Could not send response."},{status:422})}}
