"use client";
import { useEffect, useState } from "react";
type Category = { id:string; name:string };
type Question = { id:string; questionText:string; difficulty:string; status:string; sourceType:string; category:Category };
export function QuizQuestionManager() {
  const [questions,setQuestions]=useState<Question[]>([]); const [categories,setCategories]=useState<Category[]>([]); const [status,setStatus]=useState("");
  const [form,setForm]=useState({ questionText:"", explanation:"", categoryId:"", difficulty:"MEDIUM", status:"DRAFT", options:["","","",""], correct:0 });
  async function load(){const r=await fetch("/api/admin/quiz-questions",{cache:"no-store"}); const b=await r.json(); if(!r.ok) throw new Error(b.error); setQuestions(b.questions);setCategories(b.categories);setForm(f=>({...f,categoryId:f.categoryId||b.categories[0]?.id||""}));}
  useEffect(()=>{void load().catch(e=>setStatus(e.message));},[]);
  async function create(){setStatus("Saving…");const r=await fetch("/api/admin/quiz-questions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,options:form.options.map((text,i)=>({text,correct:i===form.correct}))})});const b=await r.json();if(!r.ok)return setStatus(b.error??"Could not save");setForm(f=>({...f,questionText:"",explanation:"",options:["","","",""]}));await load();setStatus("Question saved.");}
  return <div className="grid gap-5"><section className="grid gap-3 rounded-4xl bg-white p-5 shadow-card"><h2 className="text-lg font-extrabold">Add custom question</h2><textarea aria-label="Question" placeholder="Question" value={form.questionText} onChange={e=>setForm({...form,questionText:e.target.value})} className="min-h-20 rounded-xl border p-3"/><div className="grid gap-2 sm:grid-cols-2">{form.options.map((value,i)=><label key={i} className="flex items-center gap-2 rounded-xl bg-warm-50 p-2"><input type="radio" name="correct" checked={form.correct===i} onChange={()=>setForm({...form,correct:i})}/><input aria-label={`Option ${i+1}`} placeholder={`Option ${i+1}`} value={value} onChange={e=>{const options=[...form.options];options[i]=e.target.value;setForm({...form,options});}} className="min-h-10 w-full bg-transparent"/></label>)}</div><textarea aria-label="Explanation" placeholder="Explanation shown after answering" value={form.explanation} onChange={e=>setForm({...form,explanation:e.target.value})} className="min-h-16 rounded-xl border p-3"/><div className="grid gap-2 sm:grid-cols-3"><select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})} className="min-h-11 rounded-xl border px-3">{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={form.difficulty} onChange={e=>setForm({...form,difficulty:e.target.value})} className="min-h-11 rounded-xl border px-3">{["EASY","MEDIUM","HARD"].map(v=><option key={v}>{v}</option>)}</select><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="min-h-11 rounded-xl border px-3">{["DRAFT","PUBLISHED","DISABLED"].map(v=><option key={v}>{v}</option>)}</select></div><button onClick={()=>void create()} className="game-primary justify-self-end">Create question</button><p className="text-xs text-warm-500">{status}</p></section><section className="rounded-4xl bg-white p-5 shadow-card"><h2 className="text-lg font-extrabold">Question bank ({questions.length})</h2><div className="mt-3 divide-y">{questions.map(q=><article key={q.id} className="py-3"><p className="font-bold">{q.questionText}</p><p className="text-xs text-warm-500">{q.category.name} · {q.difficulty} · {q.status} · {q.sourceType}</p></article>)}</div></section></div>;
}
