"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
type Availability = { available: boolean; status: string; slug: string };
const categories = ["COMMUNITY","ENTERTAINMENT","EDUCATION","BUSINESS","CREATOR","GAMING","OTHER"];
const channels = ["TELEGRAM_CHANNEL","TELEGRAM_GROUP","TELEGRAM_BOT","TIKTOK","INSTAGRAM","YOUTUBE","X","FACEBOOK","WEBSITE","OTHER"];
export function MiniAppRequestForm({ authenticated, applicantName, username }: { authenticated: boolean; applicantName?: string; username?: string | null }) {
  const [form, setForm] = useState({ proposedName:"",requestedSlug:"",description:"",intendedAudience:"",category:"COMMUNITY",contactMethod:username?`@${username}`:"",
    primaryPromotionChannel:"TELEGRAM_CHANNEL",primaryPromotionUrl:"https://t.me/",estimatedAudienceSize:0,expectedFirstWeekUsers:1,promotionPlan:"",additionalLinks:"",
    review:false,genuineUsers:false,inactivity:false,rewards:false,terms:false });
  const [availability,setAvailability]=useState<Availability|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[submitted,setSubmitted]=useState<any>(null);
  const [deviceReady,setDeviceReady]=useState(false);
  useEffect(()=>{if(!authenticated)return;void (async()=>{try{const recovery=localStorage.getItem("ag_request_device"),response=await fetch("/api/request-device",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(recovery?{recoveryIdentifier:recovery}:{})}),body=await response.json();if(!response.ok)throw new Error(body.error??"Device verification failed");localStorage.setItem("ag_request_device",body.identifier);setDeviceReady(true)}catch(error){setMessage(error instanceof Error?error.message:"Device verification failed")}})()},[authenticated]);
  const preview=useMemo(()=>`${typeof location==="undefined"?"https://platform.example":location.origin}/${form.requestedSlug||"your-link"}`,[form.requestedSlug]);
  const set=(key:string,value:any)=>setForm((x)=>({...x,[key]:value}));
  async function checkSlug(value:string){set("requestedSlug",value);if(value.length<5)return setAvailability(null);const r=await fetch(`/api/mini-app-requests/availability?slug=${encodeURIComponent(value)}`),b=await r.json();setAvailability(b)}
  async function submit(e:React.FormEvent){e.preventDefault();if(!authenticated){setMessage("Sign in through an existing Ads Galaxy Mini App before submitting.");return}setBusy(true);setMessage("");
    const payload={...form,estimatedAudienceSize:Number(form.estimatedAudienceSize),expectedFirstWeekUsers:Number(form.expectedFirstWeekUsers),
      additionalLinks:form.additionalLinks.split(/\s+/).filter(Boolean),acknowledgements:{review:form.review,genuineUsers:form.genuineUsers,inactivity:form.inactivity,rewards:form.rewards,terms:form.terms},idempotencyKey:crypto.randomUUID()};
    const r=await fetch("/api/mini-app-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),b=await r.json();setBusy(false);if(!r.ok)return setMessage(b.error??"Could not submit request");setSubmitted(b)}
  if(submitted)return <section className="rounded-[2rem] bg-white p-7 text-center shadow-float"><h1 className="text-3xl font-black">Request Submitted</h1><p className="mt-3 text-warm-600">Your Mini App request has been submitted for review. You can return at any time to track it.</p><div className="mx-auto mt-5 max-w-sm rounded-2xl bg-warm-50 p-4 text-left text-sm"><p><b>Reference:</b> {submitted.publicReference}</p><p><b>Name:</b> {submitted.proposedName}</p><p className="break-all"><b>Path:</b> /{submitted.requestedSlug}</p><p><b>Status:</b> Submitted</p></div><Link href={`/request-mini-app/status/${submitted.publicReference}`} className="game-primary mt-5">Check Status</Link></section>;
  return <form onSubmit={submit} className="grid gap-5">
    <Section title="A. Applicant identity"><div className="grid gap-3 sm:grid-cols-2"><Field label="Applicant" value={applicantName??"Authentication required"} disabled/><Field label="Telegram username" value={username?`@${username}`:"Not available"} disabled/><Field label="Contact method" value={form.contactMethod} change={(v)=>set("contactMethod",v)} required/></div>{!authenticated&&<p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-950">You may review the form, but a trusted signed session is required for final submission.</p>}</Section>
    <Section title="B. Mini App details"><div className="grid gap-3 sm:grid-cols-2"><Field label="Proposed Mini App name" value={form.proposedName} change={(v)=>set("proposedName",v)} required/><label className="grid gap-1 text-sm font-bold">Primary category<select value={form.category} onChange={(e)=>set("category",e.target.value)} className="min-h-12 rounded-xl border bg-white px-3">{categories.map(x=><option key={x}>{x}</option>)}</select></label><Field label="Preferred Mini App path" value={form.requestedSlug} change={(v)=>void checkSlug(v.toLowerCase())} required/><div className="self-end rounded-xl bg-warm-50 p-3 text-xs"><span className="font-bold">{availability?availability.status.replaceAll("_"," "):"Enter at least 5 characters"}</span><p className="mt-1 break-all text-warm-500">{preview}</p></div><Area label="Short description" value={form.description} change={(v)=>set("description",v)} minLength={30}/><Area label="Intended audience" value={form.intendedAudience} change={(v)=>set("intendedAudience",v)} minLength={20}/></div><Help>This becomes your public Mini App link, such as <code>/creator-hub</code>. It never creates a server folder.</Help></Section>
    <Section title="C. Promotion plan"><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm font-bold">Primary promotion channel<select value={form.primaryPromotionChannel} onChange={(e)=>set("primaryPromotionChannel",e.target.value)} className="min-h-12 rounded-xl border bg-white px-3">{channels.map(x=><option key={x}>{x.replaceAll("_"," ")}</option>)}</select></label><Field label="Social/community URL" type="url" value={form.primaryPromotionUrl} change={(v)=>set("primaryPromotionUrl",v)} required/><Field label="Current audience size" type="number" value={String(form.estimatedAudienceSize)} change={(v)=>set("estimatedAudienceSize",v)} required/><Field label="Expected first-week users" type="number" value={String(form.expectedFirstWeekUsers)} change={(v)=>set("expectedFirstWeekUsers",v)} required/><div className="sm:col-span-2"><Area label="Explain how you plan to bring genuine users" value={form.promotionPlan} change={(v)=>set("promotionPlan",v)} minLength={100} maxLength={2000}/></div><div className="sm:col-span-2"><Area label="Additional HTTPS links, separated by spaces" value={form.additionalLinks} change={(v)=>set("additionalLinks",v)}/></div></div><Help>Describe real channels and methods. Fake accounts, bots and artificial traffic are not allowed. First-week users are an estimate, not a guaranteed commitment.</Help></Section>
    <Section title="D. Platform expectations"><div className="grid gap-3">{[["review","Submitting does not guarantee approval."],["genuineUsers","I will use genuine users, not bots or fraudulent traffic."],["inactivity","Inactive Mini Apps may be paused under the activity policy."],["rewards","Ad availability and rewards remain subject to verification and platform rules."],["terms","I agree to the platform Terms and Privacy Policy."]].map(([key,text])=><label key={key} className="flex gap-3 rounded-xl bg-warm-50 p-3 text-sm"><input type="checkbox" checked={Boolean((form as any)[key])} onChange={(e)=>set(key,e.target.checked)} required className="mt-1 h-5 w-5 accent-teal-700"/><span>{text}</span></label>)}</div></Section>
    <button disabled={busy||!authenticated||availability?.available===false} className="game-primary min-h-14 text-base disabled:opacity-45">{busy?"Submitting…":"Submit Request"}</button><p role="alert" className="text-sm font-bold text-coral-600">{message}</p>
  </form>
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-[1.5rem] bg-white p-5 shadow-card"><h2 className="mb-4 text-xl font-black">{title}</h2>{children}</section>}
function Field({label,value,change,disabled,type="text",required=false}:{label:string;value:string;change?:(v:string)=>void;disabled?:boolean;type?:string;required?:boolean}){return <label className="grid gap-1 text-sm font-bold">{label}<input type={type} value={value} disabled={disabled} required={required} onChange={(e)=>change?.(e.target.value)} className="min-h-12 min-w-0 rounded-xl border bg-white px-3 disabled:bg-warm-50"/></label>}
function Area({label,value,change,minLength,maxLength}:{label:string;value:string;change:(v:string)=>void;minLength?:number;maxLength?:number}){return <label className="grid gap-1 text-sm font-bold">{label}<textarea value={value} onChange={(e)=>change(e.target.value)} minLength={minLength} maxLength={maxLength} required={Boolean(minLength)} rows={4} className="min-w-0 rounded-xl border px-3 py-3"/></label>}
function Help({children}:{children:React.ReactNode}){return <p className="mt-4 rounded-xl bg-teal-50 p-3 text-xs leading-5 text-teal-950">{children}</p>}
