import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BadgeCheck, Bot, Gamepad2, ListChecks, Megaphone, ShieldCheck, Users, WalletCards } from "lucide-react";
export const metadata: Metadata = {
  title: "Launch Your Telegram Mini App",
  description: "Request a managed Telegram Mini App with games, tasks, Wallet tools, rewards, advertising integration and a dedicated Admin workspace.",
  alternates: { canonical: "/" },
  openGraph: { title: "Launch Your Telegram Mini App", description: "A managed Mini App platform for communities, creators and businesses.", type: "website" },
};
const features = [
  [Gamepad2, "Games", "Memory Match, Quiz Challenge and Catch Rush with platform-controlled mechanics, scoring and reward safety."],
  [ListChecks, "Tasks", "Create approved engagement tasks while the platform enforces reward and verification limits."],
  [WalletCards, "Wallet", "Users can view points, supported conversions, balances and withdrawal status through a controlled Wallet."],
  [Users, "Tenant Admin", "Manage users, supported rewards, tasks, Telegram setup, announcements and tenant settings."],
  [Bot, "Ads Galaxy", "Connect the shared Ads Galaxy Mini App ID for eligible sponsored ad and reward flows."],
  [Megaphone, "Sponsored Content", "Platform-sponsored announcements and promotional cards may appear across participating Mini Apps."],
  [ShieldCheck, "Security", "Tenant data is isolated, financial records use immutable ledgers, and protected credentials remain encrypted."],
] as const;
export default function Home() {
  return <main className="public-site min-h-dvh overflow-x-hidden bg-[#faf9f7] text-[#14201e]">
    <nav className="mx-auto flex max-w-6xl items-center justify-between px-4 py-5"><Link href="/" className="flex items-center gap-2 font-black"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-teal-600 text-white"><BadgeCheck /></span>Ads Galaxy</Link><div className="flex items-center gap-2"><Link href="/request-mini-app/status" className="hidden px-3 py-2 text-sm font-bold sm:block">Request Status</Link><Link href="/request-mini-app" className="rounded-xl bg-teal-700 px-4 py-3 text-sm font-black text-white">Request Your Mini App</Link></div></nav>
    <section className="mx-auto grid max-w-6xl gap-10 px-4 pb-20 pt-14 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:pt-24">
      <div><p className="text-xs font-black uppercase tracking-[.22em] text-teal-700">Launch your Telegram community</p><h1 className="mt-4 max-w-3xl text-balance text-5xl font-black leading-[1.02] sm:text-6xl">Get Your Own Telegram Mini App in Minutes</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-warm-600">Request a professionally managed Telegram Mini App with games, tasks, rewards, wallet tools and advertising features—all from one secure platform.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/request-mini-app" className="game-primary min-h-14 px-6 text-base">Get My Free Mini App <ArrowRight size={18} /></Link><a href="#how" className="game-secondary min-h-14 px-6 text-base">See How It Works</a></div><p className="mt-5 text-sm font-bold text-warm-500">Start for free. No separate hosting or duplicated application setup required.</p></div>
      <div className="relative rounded-[2rem] border border-white bg-white p-6 shadow-float"><div className="absolute -right-8 -top-8 h-32 w-32 rounded-full bg-teal-100 blur-2xl" /><p className="text-xs font-black uppercase text-coral-500">One platform · your community</p><div className="mt-5 grid gap-3">{["Dedicated public Mini App link","Administrator workspace","Games, tasks and Wallet tools","Platform-managed security and reward controls"].map((x, i) => <div key={x} className="flex items-center gap-3 rounded-2xl bg-warm-50 p-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-teal-100 font-black text-teal-700">{i + 1}</span><strong className="text-sm">{x}</strong></div>)}</div></div>
    </section>
    <section id="how" className="bg-white py-20"><div className="mx-auto max-w-6xl px-4"><p className="text-xs font-black uppercase tracking-[.2em] text-teal-700">How it works</p><h2 className="mt-2 text-3xl font-black">From request to launch</h2><div className="mt-8 grid gap-4 md:grid-cols-4">{[["Open through Telegram","Use your verified Telegram account to begin securely."],["Submit your free request","Choose your Mini App name, category and preferred public path."],["We review and prepare it","Ads Galaxy reviews the request and creates the tenant securely. Approval is not guaranteed."],["Launch and manage","Connect your Telegram bot and manage games, users, tasks, wallet settings and monetization."]].map(([title, body], i) => <article key={title} className="rounded-3xl border border-warm-100 p-5"><span className="text-3xl font-black text-teal-200">0{i + 1}</span><h3 className="mt-3 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-warm-600">{body}</p></article>)}</div><p className="mt-6 rounded-2xl bg-amber-50 p-4 text-sm font-bold text-amber-950">Each Telegram account and device may have only one active free Mini App request.</p></div></section>
    <section id="features" className="py-20"><div className="mx-auto max-w-6xl px-4"><p className="text-xs font-black uppercase tracking-[.2em] text-teal-700">What is included</p><h2 className="mt-2 text-3xl font-black">A complete managed Mini App</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{features.map(([Icon, title, body]) => <article key={title} className="rounded-3xl bg-white p-5 shadow-card"><Icon className="text-teal-700" /><h3 className="mt-4 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-warm-600">{body}</p></article>)}</div><p className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm text-amber-950">Ad availability and earnings depend on campaigns, verified activity, traffic quality and active provider rules. No income or ad availability is guaranteed.</p></div></section>
    <section className="bg-[#14201e] py-20 text-white"><div className="mx-auto grid max-w-6xl gap-8 px-4 lg:grid-cols-2"><div><p className="text-xs font-black uppercase tracking-[.2em] text-teal-300">Clear responsibilities</p><h2 className="mt-2 text-3xl font-black">What Administrators can manage</h2><ul className="mt-5 grid gap-2 text-sm text-white/75">{["Tenant profile and permitted Telegram bot settings","Tasks, tenant users and announcements","Tenant-funded reward values within platform limits","Supported Wallet and OxaPay settings","Maintenance message and shared Ads Galaxy Mini App ID"].map((x) => <li key={x}>✓ {x}</li>)}</ul></div><div className="rounded-3xl bg-white/8 p-6"><h3 className="font-black">Platform-controlled safeguards</h3><p className="mt-3 text-sm leading-7 text-white/65">Platform security, global game mechanics, provider verification, financial ledgers, sponsored campaigns, other tenants and emergency controls remain managed by the platform team.</p></div></div></section>
    <section className="py-20"><div className="mx-auto grid max-w-6xl gap-8 px-4 lg:grid-cols-2"><div><h2 className="text-3xl font-black">Who should apply?</h2><p className="mt-4 leading-7 text-warm-600">Telegram community and channel owners, bot owners, creators, community managers, businesses and partners with an existing audience or a realistic promotion strategy.</p><p className="mt-4 rounded-2xl bg-white p-4 text-sm font-bold shadow-card">Approved Mini Apps are expected to remain active. Inactive tenants may be temporarily paused under the platform activity policy.</p></div><div><h2 className="text-3xl font-black">What you will provide</h2><ul className="mt-4 grid gap-2 text-sm text-warm-600"><li>• Requested Mini App name and preferred path</li><li>• Trusted Telegram identity and contact method</li><li>• Primary community or social link</li><li>• Audience estimate and genuine promotion plan</li><li>• Agreement to platform rules</li></ul></div></div></section>
    <section className="mx-auto max-w-6xl px-4 pb-20"><div className="rounded-[2rem] bg-teal-700 p-8 text-white sm:p-12"><h2 className="text-3xl font-black">Ready to Request Your Mini App?</h2><p className="mt-3 text-teal-50">Submit your preferred Mini App name, link and promotion plan for review.</p><div className="mt-6 flex flex-col gap-3 sm:flex-row"><Link href="/request-mini-app" className="rounded-xl bg-white px-5 py-4 text-center font-black text-teal-800">Start Your Request</Link><Link href="/request-mini-app/status" className="rounded-xl border border-white/30 px-5 py-4 text-center font-black">Check Request Status</Link></div></div></section>
    <footer className="border-t bg-white"><div className="mx-auto flex max-w-6xl flex-col gap-4 px-4 py-8 text-sm sm:flex-row sm:items-center sm:justify-between"><strong>Ads Galaxy Platform</strong><div className="flex flex-wrap gap-4"><Link href="/request-mini-app">Request Mini App</Link><Link href="/request-mini-app/status">Request Status</Link></div><span className="text-warm-400">© {new Date().getFullYear()} Ads Galaxy</span></div></footer>
  </main>;
}
