"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, Bomb, CircleDollarSign, Coins, Gem, Gift, Pause, Play, RotateCcw, Star, Trophy } from "lucide-react";
import { showAdsGalaxy } from "@/lib/ads/adsgalaxy-provider";

type Event = { id:string;itemType:string;itemClass:string;normalizedX:number;spawnedAtOffsetMs:number;expiresAtOffsetMs:number;fallDurationMs:number;status:string;required:boolean };
type Claim = { id:string;tapSpawnEventId:string;status:string };
type Session = { id:string;status:string;level:number;score:number;combo:number;finalPoints:number;stars:number|null;activeElapsedMs:number|null;bestTimeMs:number|null;failureCause:string|null;version:number;events:Event[];claims:Claim[];authoritativeElapsedMs:number;activeEventCount:number;nextEventSpawnOffsetMs:number|null };
const icons:Record<string,typeof Gem>={COIN:Coins,MONEY:CircleDollarSign,GEM:Gem,STAR:Star,SPONSORED_CRATE:Gift,BOMB:Bomb};
const labels:Record<string,string>={COIN:"Coin",MONEY:"Money reward",GEM:"Gem",STAR:"Star",SPONSORED_CRATE:"Gift",BOMB:"Bomb"};
const format=(ms:number|null)=>`${Math.max(0,ms??0)/1000}`.replace(/(\.\d).*$/,"$1")+"s";

export function TapGame(){
  const id=useMemo(()=>typeof window==="undefined"?null:new URLSearchParams(window.location.search).get("session"),[]);
  const [session,setSession]=useState<Session|null>(null),[elapsed,setElapsed]=useState(0),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[recovery,setRecovery]=useState(false);
  const processing=useRef(new Set<string>()),sync=useRef({elapsed:0,at:Date.now()});
  const load=useCallback(async()=>{if(!id){setRecovery(true);return setMessage("This game session can no longer be resumed.");}const r=await fetch(`/api/games/tap-collector/sessions/${id}`,{cache:"no-store"}),b=await r.json();if(!r.ok){setRecovery(true);setSession(null);return setMessage(b.error??"We couldn’t synchronize this game session.");}sync.current={elapsed:Math.max(0,b.authoritativeElapsedMs||0),at:Date.now()};setElapsed(sync.current.elapsed);setSession(b);setRecovery(false)},[id]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>{if(session?.status!=="ACTIVE")return;const timer=window.setInterval(()=>setElapsed(sync.current.elapsed+Math.max(0,Date.now()-sync.current.at)),50);return()=>window.clearInterval(timer)},[session?.status]);
  useEffect(()=>{const visibility=()=>{if(!id||!session||!["ACTIVE","PAUSED"].includes(session.status))return;void fetch(`/api/games/tap-collector/sessions/${id}/${document.hidden?"pause":"resume"}`,{method:"POST"}).then(load)};document.addEventListener("visibilitychange",visibility);return()=>document.removeEventListener("visibilitychange",visibility)},[id,load,session]);
  const action=async(name:"start"|"pause"|"resume"|"abandon")=>{if(!id)return;setBusy(true);const r=await fetch(`/api/games/tap-collector/sessions/${id}/${name}`,{method:"POST"});if(r.ok)await load();else setMessage((await r.json()).error??"Could not update game.");setBusy(false)};
  const resolve=useCallback(async(event:Event,eventType:"TAP"|"MISS")=>{if(!session||session.status!=="ACTIVE"||processing.current.has(event.id))return;processing.current.add(event.id);const r=await fetch(`/api/games/tap-collector/sessions/${session.id}/events`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({spawnEventId:event.id,eventType,idempotencyKey:crypto.randomUUID(),version:session.version})}),b=await r.json();processing.current.delete(event.id);if(!r.ok){setMessage("We couldn’t synchronize this game session.");await load();return;}sync.current={elapsed:b.authoritativeElapsedMs,at:Date.now()};setSession(b);setMessage(eventType==="MISS"?(event.required?`You missed the ${labels[event.itemType]??"collectible"}.`:"Bomb avoided."):(event.itemType==="BOMB"?"You tapped the Bomb.":`${labels[event.itemType]} collected!`))},[load,session]);
  useEffect(()=>{if(!session||session.status!=="ACTIVE"||busy)return;const expired=session.events.find(e=>e.status==="SCHEDULED"&&elapsed>=e.expiresAtOffsetMs+160&&!processing.current.has(e.id));if(expired)void resolve(expired,"MISS");else if(session.events.every(e=>e.status!=="SCHEDULED"))void fetch(`/api/games/tap-collector/sessions/${session.id}/complete`,{method:"POST"}).then(load)},[busy,elapsed,load,resolve,session]);
  async function watchAd(claim:Claim){if(!session||busy)return;setBusy(true);const request=await fetch(`/api/reward-claims/${claim.id}/request-ad`,{method:"POST"}),data=await request.json();if(!request.ok){setBusy(false);return setMessage(data.error)}const outcome=await showAdsGalaxy(data.adsGalaxyMiniAppId);const result=await fetch(`/api/reward-claims/${claim.id}/browser-result`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId:data.requestId,outcome:outcome.status,...(outcome.status==="COMPLETED"?{providerRequestId:outcome.providerRequestId}:{})})});setMessage((await result.json()).message??"Reward claim updated.");setBusy(false);await action("resume")}
  if(recovery||(!session&&message))return <Recovery message={message} retry={load}/>;
  if(!session)return <main className="grid min-h-dvh place-items-center"><p className="font-bold">Restoring Catch Rush…</p></main>;
  if(session.status==="COMPLETED")return <Result title="Level Complete" session={session}/>;
  if(session.status==="GAME_OVER")return <Result title={session.failureCause==="BOMB_TAPPED"?"You tapped the Bomb.":"A required collectible was missed."} session={session} failed/>;
  const moneyClaim=session.claims.find(c=>!["CREDITED","VERIFIED"].includes(c.status));
  const visible=session.status==="ACTIVE"?session.events.filter(e=>e.status==="SCHEDULED"&&elapsed>=e.spawnedAtOffsetMs&&elapsed<=e.expiresAtOffsetMs+160):[];
  return <main className="fixed inset-0 z-40 flex min-h-[100dvh] w-full select-none flex-col overflow-hidden bg-[#dff6ef] pt-[env(safe-area-inset-top)]">
    <header className="relative z-20 grid shrink-0 grid-cols-[44px_1fr_44px] items-center bg-ink px-2 py-2 text-white shadow-lg sm:px-5"><button aria-label="Exit game" onClick={()=>void action("abandon")} className="grid h-10 place-items-center"><ArrowLeft/></button><div className="grid grid-cols-4 gap-1 text-center">{[["Level",session.level],["Score",session.score],["Combo",`×${session.combo}`],["Time",format(session.status==="READY"?0:elapsed)]].map(([label,value])=><div key={label}><small className="block text-[9px] uppercase text-white/55">{label}</small><b className="text-sm sm:text-base">{value}</b></div>)}</div><button aria-label={session.status==="PAUSED"?"Resume":"Pause"} disabled={session.status==="READY"} onClick={()=>void action(session.status==="PAUSED"?"resume":"pause")} className="grid h-10 place-items-center">{session.status==="PAUSED"?<Play/>:<Pause/>}</button></header>
    <section aria-label="Catch Rush falling-object arena" className="catch-rush-arena relative min-h-0 flex-1 overflow-hidden bg-[radial-gradient(circle_at_top,#cbfff4,#eef9f7_45%,#fff3d6)] touch-none">
      <div className="absolute inset-x-0 bottom-0 z-10 h-2 bg-coral-400/60"/>
      {visible.map(event=>{const Icon=icons[event.itemType]??Gem,delay=Math.max(0,elapsed-event.spawnedAtOffsetMs);return <button key={event.id} aria-label={labels[event.itemType]??"Collectible"} onPointerDown={pointer=>{pointer.preventDefault();void resolve(event,"TAP")}} className={`catch-rush-object ${event.itemClass.toLowerCase()} absolute top-0 z-20 grid h-14 w-14 -translate-x-1/2 place-items-center rounded-2xl border-2 shadow-float sm:h-16 sm:w-16`} style={{left:`${event.normalizedX/100}%`,animationDuration:`${event.fallDurationMs}ms`,animationDelay:`-${delay}ms`}}><Icon size={event.itemType==="MONEY"?32:27}/></button>})}
      {session.status==="READY"&&<Overlay><Play size={46} className="text-teal-600"/><h1 className="text-3xl font-black">Level {session.level}</h1><p className="text-sm text-warm-600">Score 0 · Combo ×0 · Time 0.0s</p><button disabled={busy} onClick={()=>void action("start")} className="game-primary w-full justify-center">Start Game</button></Overlay>}
      {session.status==="PAUSED"&&!moneyClaim&&<Overlay><Pause size={42}/><h2 className="text-2xl font-black">Game Paused</h2><button onClick={()=>void action("resume")} className="game-primary w-full justify-center">Resume</button><Link href="/games/tap-collector" className="game-secondary w-full justify-center">Exit</Link></Overlay>}
      {session.status==="PAUSED"&&moneyClaim&&<Overlay><CircleDollarSign size={42} className="text-emerald-600"/><h2 className="text-2xl font-black">Money Reward Found</h2><p className="text-center text-xs text-warm-600">Money credits only after trusted provider verification.</p><button disabled={busy} onClick={()=>void watchAd(moneyClaim)} className="game-primary w-full justify-center">Watch Ad and Claim</button><button onClick={()=>void action("resume")} className="game-secondary w-full justify-center">Continue Without Claim</button></Overlay>}
      {message&&<p aria-live="polite" className="absolute inset-x-3 bottom-4 z-30 rounded-2xl bg-white/95 p-3 text-center text-xs font-bold text-warm-700 shadow-card">{message}</p>}
    </section>
  </main>
}
function Overlay({children}:{children:React.ReactNode}){return <div className="absolute inset-0 z-40 grid place-items-center bg-ink/65 p-4"><section className="grid w-full max-w-sm justify-items-center gap-4 rounded-3xl bg-white p-6 shadow-float">{children}</section></div>}
function Recovery({message,retry}:{message:string;retry():Promise<void>}){return <main className="grid min-h-dvh place-items-center p-4"><section className="w-full max-w-sm rounded-3xl bg-white p-6 text-center shadow-card"><RotateCcw className="mx-auto text-coral-500"/><h1 className="mt-3 text-xl font-black">Session unavailable</h1><p className="mt-2 text-sm text-warm-600">{message||"This game session can no longer be resumed."}</p><div className="mt-5 grid gap-2"><button onClick={()=>void retry()} className="game-primary justify-center">Retry</button><Link href="/games/tap-collector" className="game-secondary justify-center">Start New Game</Link><Link href="/games" className="text-sm font-bold text-warm-500">Return to Games</Link></div></section></main>}
function Result({title,session,failed=false}:{title:string;session:Session;failed?:boolean}){return <main className="grid min-h-dvh place-items-center p-4"><section className="w-full max-w-md rounded-[2rem] bg-white p-7 text-center shadow-float">{failed?<Bomb className="mx-auto text-coral-500" size={44}/>:<Trophy className="mx-auto text-amber-500" size={44}/>}<h1 className="mt-4 text-3xl font-black">{title}</h1><p className="mt-2">{format(session.activeElapsedMs)} · {session.finalPoints} points</p><div className="mt-5 grid gap-2"><Link href="/games/tap-collector" className="game-primary justify-center">{failed?"Restart Level":"Next Level"}</Link><Link href="/games/tap-collector" className="game-secondary justify-center">Return to Levels</Link></div></section></main>}
