"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, X } from "lucide-react";

type Action="SUSPEND"|"RESTORE"|"MAINTENANCE_ON"|"MAINTENANCE_OFF"|"RESET_BOT"|"RESET_OXAPAY"|"RESET_ADS_GALAXY"|"INACTIVITY_EXEMPT";
const labels:Record<Action,string>={SUSPEND:"Suspend tenant",RESTORE:"Resume Tenant",MAINTENANCE_ON:"Enable maintenance",MAINTENANCE_OFF:"Disable maintenance",RESET_BOT:"Reset bot token",RESET_OXAPAY:"Reset OxaPay",RESET_ADS_GALAXY:"Reset Ads Galaxy ID",INACTIVITY_EXEMPT:"Exempt from inactivity suspension"};
export function TenantActions({tenantId,status,maintenance}:{tenantId:string;status:string;maintenance:boolean}){
  const ref=useRef<HTMLDialogElement>(null),router=useRouter(),[action,setAction]=useState<Action|null>(null),[reason,setReason]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  function open(next:Action){setAction(next);setReason("");setMessage("");ref.current?.showModal()}
  async function submit(){if(!action||busy)return;setBusy(true);const response=await fetch(`/api/super-admin/tenants/${tenantId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,reason,confirm:true,...(action==="INACTIVITY_EXEMPT"?{expiresAt:null}:{})})}),body=await response.json().catch(()=>({}));setBusy(false);if(!response.ok)return setMessage(body.error??"Action failed.");ref.current?.close();router.refresh()}
  return <><div className="flex flex-wrap gap-2"><button className="game-secondary" onClick={()=>open(status==="ACTIVE"?"SUSPEND":"RESTORE")}>{status==="ACTIVE"?"Suspend":"Resume Tenant"}</button><button className="game-secondary" onClick={()=>open(maintenance?"MAINTENANCE_OFF":"MAINTENANCE_ON")}>{maintenance?"Disable maintenance":"Enable maintenance"}</button><button className="game-secondary" onClick={()=>open("INACTIVITY_EXEMPT")}>Inactivity exemption</button><button className="game-secondary" onClick={()=>open("RESET_BOT")}>Reset bot</button><button className="game-secondary" onClick={()=>open("RESET_OXAPAY")}>Reset OxaPay</button><button className="game-secondary" onClick={()=>open("RESET_ADS_GALAXY")}>Reset Ads Galaxy</button></div>
  <dialog ref={ref} className="m-auto w-[min(30rem,calc(100%-1rem))] rounded-3xl bg-[var(--sa-surface)] p-0 text-[var(--sa-text)] shadow-2xl backdrop:bg-slate-950/60"><div className="flex gap-3 border-b border-[var(--sa-border)] p-5"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-coral-50 text-coral-500"><AlertTriangle/></span><div><h2 className="font-black">{action?labels[action]:"Confirm action"}</h2><p className="sa-muted mt-1 text-xs">This global action is audited. Financial and provider history will be preserved.</p></div><button className="sa-icon ml-auto shrink-0" onClick={()=>ref.current?.close()}><X/></button></div><div className="grid gap-3 p-5"><label className="text-xs font-bold">Reason<textarea value={reason} onChange={e=>setReason(e.target.value)} rows={3} maxLength={300} className="mt-1 w-full rounded-xl border border-[var(--sa-border)] bg-[var(--sa-surface)] p-3"/></label><p className="text-xs font-bold text-coral-500">{message}</p><div className="flex justify-end gap-2"><button className="game-secondary" onClick={()=>ref.current?.close()}>Cancel</button><button disabled={reason.trim().length<5||busy} className="game-primary disabled:opacity-50" onClick={()=>void submit()}>{busy?"Applying…":"Confirm"}</button></div></div></dialog></>
}
