import { describe,expect,it } from "vitest";
import { normalizeRequestSlug, safeContactUrl, validRequestSlug, requestSchema } from "./policy";
describe("Mini App request policy",()=>{
  it("accepts safe custom paths",()=>{for(const slug of ["myapp","creator-hub","games247","my-community"])expect(validRequestSlug(slug)).toBe(true)});
  it("rejects unsafe, numeric-only and reserved paths",()=>{for(const slug of ["12345","admin","super-admin","request-mini-app","../miniapp","my app","-myapp","myapp-","my--app","https://example.com"])expect(validRequestSlug(slug)).toBe(false)});
  it("normalizes display input without making it authoritative",()=>{expect(normalizeRequestSlug(" Creator Hub ")).toBe("creator-hub")});
  it("accepts HTTPS and rejects unsafe URL protocols",()=>{expect(safeContactUrl("https://t.me/community")).toContain("https://");expect(safeContactUrl("javascript:alert(1)")).toBeNull();expect(safeContactUrl("http://example.com")).toBeNull()});
  it("requires every acknowledgement and a meaningful promotion plan",()=>{const base={proposedName:"Creator Hub",requestedSlug:"creator-hub",description:"A community engagement Mini App for creators.",intendedAudience:"Independent creators and their active audiences.",category:"CREATOR",contactMethod:"@creator",primaryPromotionChannel:"TELEGRAM_CHANNEL",primaryPromotionUrl:"https://t.me/creator",estimatedAudienceSize:1000,expectedFirstWeekUsers:100,promotionPlan:"We will announce the Mini App in our Telegram channel, publish weekly game events, explain the Wallet rules, and invite genuine community members through our established content schedule.",additionalLinks:[],idempotencyKey:"7bea1506-b8a4-4e19-8879-a62c9f77ebc4"};expect(()=>requestSchema.parse({...base,acknowledgements:{review:true,genuineUsers:true,inactivity:true,rewards:true,terms:true}})).not.toThrow();expect(()=>requestSchema.parse({...base,acknowledgements:{review:true,genuineUsers:true,inactivity:true,rewards:true,terms:false}})).toThrow()});
});
