import { describe,expect,it } from "vitest";
import { normalizeRequestSlug, normalizeTelegramUsername, safeContactUrl, validRequestSlug, requestSchema } from "./policy";
import { createStatusAccessToken, hashDeviceIdentifier, hashStatusAccessToken, requestAccessAllowed, requestBlocksAnother, validDeviceIdentifier } from "./device";
describe("Mini App request policy",()=>{
  it("accepts a browser payload without Telegram identity, contact method, or session data",()=>{const payload={applicantName:"Browser Applicant",telegramUsername:"",proposedName:"Creator Hub",requestedSlug:"creator-hub",description:"A community engagement Mini App for creators.",intendedAudience:"Independent creators and their active audiences.",category:"CREATOR",primaryPromotionChannel:"OTHER",primaryPromotionUrl:"https://example.com/community",estimatedAudienceSize:0,expectedFirstWeekUsers:0,promotionPlan:"We will promote the Mini App through our established community channels, publish scheduled events, and invite genuine users with clear instructions.",additionalLinks:[],idempotencyKey:"7bea1506-b8a4-4e19-8879-a62c9f77ebc4",acknowledgements:{review:true,genuineUsers:true,inactivity:true,rewards:true,terms:true}};expect(requestSchema.safeParse(payload).success).toBe(true)});
  it("normalizes and validates an optional Telegram username",()=>{expect(normalizeTelegramUsername(" @ada_user ")).toBe("ada_user");expect(requestSchema.safeParse({...validPayload(),telegramUsername:"bad-name"}).success).toBe(false)});
  it("accepts safe custom paths",()=>{for(const slug of ["myapp","creator-hub","games247","my-community"])expect(validRequestSlug(slug)).toBe(true)});
  it("rejects unsafe, numeric-only and reserved paths",()=>{for(const slug of ["12345","admin","super-admin","request-mini-app","../miniapp","my app","-myapp","myapp-","my--app","https://example.com"])expect(validRequestSlug(slug)).toBe(false)});
  it("normalizes display input without making it authoritative",()=>{expect(normalizeRequestSlug(" Creator Hub ")).toBe("creator-hub")});
  it("accepts HTTPS and rejects unsafe URL protocols",()=>{expect(safeContactUrl("https://t.me/community")).toContain("https://");expect(safeContactUrl("javascript:alert(1)")).toBeNull();expect(safeContactUrl("http://example.com")).toBeNull()});
  it("requires every acknowledgement and a meaningful promotion plan",()=>{const base=validPayload();expect(()=>requestSchema.parse(base)).not.toThrow();expect(()=>requestSchema.parse({...base,acknowledgements:{...base.acknowledgements,terms:false}})).toThrow()});
  it("deduplicates HTTPS additional links and rejects insecure links",()=>{expect(requestSchema.parse({...validPayload(),additionalLinks:["https://example.com/a","https://example.com/a"]}).additionalLinks).toHaveLength(1);expect(requestSchema.safeParse({...validPayload(),additionalLinks:["http://example.com"]}).success).toBe(false)});
});
function validPayload(){return{applicantName:"Ada Applicant",telegramUsername:"@ada_user",proposedName:"Creator Hub",requestedSlug:"creator-hub",description:"A community engagement Mini App for creators.",intendedAudience:"Independent creators and their active audiences.",category:"CREATOR" as const,primaryPromotionChannel:"TELEGRAM_CHANNEL" as const,primaryPromotionUrl:"https://t.me/creator",estimatedAudienceSize:0,expectedFirstWeekUsers:0,promotionPlan:"We will announce the Mini App in our established community, publish weekly game events, explain the rules clearly, and invite genuine community members through our content schedule.",additionalLinks:[],idempotencyKey:"7bea1506-b8a4-4e19-8879-a62c9f77ebc4",acknowledgements:{review:true as const,genuineUsers:true as const,inactivity:true as const,rewards:true as const,terms:true as const}}}
describe("Mini App request device policy",()=>{
  it("accepts only random UUID device identifiers",()=>{expect(validDeviceIdentifier("550e8400-e29b-41d4-a716-446655440000")).toBe(true);expect(validDeviceIdentifier("browser-fingerprint")).toBe(false)});
  it("stores only a keyed hash",()=>{process.env.DEVICE_IDENTIFIER_HASH_SECRET="test-device-secret-that-is-longer-than-thirty-two-characters";const raw="550e8400-e29b-41d4-a716-446655440000",hash=hashDeviceIdentifier(raw);expect(hash).toHaveLength(64);expect(hash).not.toContain(raw);delete process.env.DEVICE_IDENTIFIER_HASH_SECRET});
  it("blocks active reviews and approved active tenants but releases terminal requests",()=>{expect(requestBlocksAnother("SUBMITTED")).toBe(true);expect(requestBlocksAnother("UNDER_REVIEW")).toBe(true);expect(requestBlocksAnother("INFORMATION_REQUIRED")).toBe(true);expect(requestBlocksAnother("APPROVED","ACTIVE")).toBe(true);expect(requestBlocksAnother("APPROVED","ARCHIVED")).toBe(false);expect(requestBlocksAnother("REJECTED")).toBe(false);expect(requestBlocksAnother("CANCELED")).toBe(false)});
  it("requires both the correct browser device and private status token",()=>{process.env.DEVICE_IDENTIFIER_HASH_SECRET="test-device-secret-that-is-longer-than-thirty-two-characters";const token=createStatusAccessToken(),tokenHash=hashStatusAccessToken(token),base={requestUserId:null,requestDeviceHash:"device-a",expectedTokenHash:tokenHash};expect(requestAccessAllowed({...base,suppliedDeviceHash:"device-a",suppliedTokenHash:tokenHash})).toBe(true);expect(requestAccessAllowed({...base,suppliedDeviceHash:"device-b",suppliedTokenHash:tokenHash})).toBe(false);expect(requestAccessAllowed({...base,suppliedDeviceHash:"device-a"})).toBe(false);delete process.env.DEVICE_IDENTIFIER_HASH_SECRET});
  it("allows the linked Telegram identity independently of browser status credentials",()=>{expect(requestAccessAllowed({requestUserId:"user-a",sessionUserId:"user-a",requestDeviceHash:"device-a",expectedTokenHash:"token"})).toBe(true);expect(requestAccessAllowed({requestUserId:"user-a",sessionUserId:"user-b",requestDeviceHash:"device-a",expectedTokenHash:"token"})).toBe(false)});
});
